# Generated by Django 2.0.5 on 2018-05-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='nutriscore',
            field=models.CharField(max_length=10),
        ),
    ]
