# Generated by Django 2.0.5 on 2018-05-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments_manager', '0002_auto_20180518_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='nutriscore',
            field=models.CharField(max_length=1),
        ),
    ]
