# Generated by Django 2.0.5 on 2018-05-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments_manager', '0005_auto_20180521_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='code',
            field=models.CharField(default='0122', max_length=15),
        ),
    ]
