# Generated by Django 2.0.5 on 2018-05-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments_manager', '0006_auto_20180521_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='url_off',
            field=models.CharField(default='https://fr.openfoodfacts.org/', max_length=200),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
