# Generated by Django 2.0.5 on 2018-05-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments_manager', '0003_auto_20180518_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='code',
            field=models.IntegerField(default='0122'),
        ),
    ]
