# Generated by Django 2.0.5 on 2018-05-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments_manager', '0007_auto_20180524_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='url_off',
            field=models.CharField(max_length=200),
        ),
    ]
