# Generated by Django 2.0.5 on 2018-05-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliments_manager', '0008_auto_20180524_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='url_off',
            new_name='image',
        ),
    ]
