# Generated by Django 2.0.5 on 2018-05-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments_manager', '0009_auto_20180524_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='code',
            field=models.CharField(max_length=13),
        ),
    ]
